before_script:
  - docker ps
  - ./code/my-demo-app/docker_stop_rm_app.sh

stages:
  - build
  - run

build_image:
  stage: build
  script:
    - ./code/my-demo-app/docker_build.sh

run_with_vault:
  stage: run
  script:
    - ./code/my-demo-app/docker_run.sh
